build:
  nodes:
    analysis:
      environment:
        php:
          version: 8.1
          pecl_extensions:
            - zip
      tests:
        override:
          - php-scrutinizer-run

filter:
    excluded_paths:
        - 'Documentation/*'
        - 'Tests/*'
    paths:
        - 'Classes/*'
tools:
    php_cpd:
        enabled: true

    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2

    php_cs_fixer:
        enabled: true

    php_mess_detector:
        enabled: true
        config:
            controversial_rules:
                superglobals: false

    php_analyzer:
        enabled: true

    sensiolabs_security_checker: true
