services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DERHANSEN\SfEventMgt\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    DERHANSEN\SfEventMgt\Command\CleanupCommand:
        tags:
            - name: 'console.command'
              command: 'sf_event_mgt:cleanup'
              schedulable: true
